data:
  boundary_points: 2048
  grid:
    nx: 50
    ny: 50
  mix:
    noise_clean: 0.01
    noise_noisy: 1.0
    ratio_clean: 0.4
  pde_points: 8192
finetune:
  epochs: 2000
  lambda_bdy: 1.0
  lambda_pde: 0.001
  lr: 0.001
model:
  hidden_dim: 100
  hidden_layers: 5
  in_dim: 2
  out_dim: 2
partition:
  threshold: 0.01
  w_data: 1.0
  w_res: 1.0
pruning:
  alpha: 0.02
  layers:
  - 0
  - 8
  num_iter: 20
  strategy: iterative
seed: 42
training:
  epochs: 20000
  lambda_bdy: 1.0
  lambda_pde: 1.0
  lr: 0.001
