data:
  noise_clean: 0.01
  noise_noisy: 0.5
  obs_circle:
    center:
    - 0.5
    - 0.5
    radius: 0.25
    resolution: 40
  pde_points: 1280
  ratio_clean: 0.8
  test_grid: 200
fine_tune_pruned:
  adam_epochs: 2000
  lambda_d: 1.0
  lambda_r: 0.001
  lbfgs_iter: 500
  lr_adam: 0.001
model:
  hidden_dim: 100
  hidden_layers: 5
  in_dim: 2
  out_dim: 3
partition:
  eps: 0.1
  w_data: 1.0
  w_res: 0.001
pruning:
  alpha: 0.05
  layers:
  - 0
  - 2
  - 4
  - 6
  - 8
  num_iter: 20
  strategy: iterative
seed: 42
training:
  adaptive_eps: 0.001
  lambda_d_max: 1000
  lbfgs_max_iter: 5000
  lr_pretrain: 0.001
  pretrain_epochs: 20000
