data:
  T_final: 1.0
  boundary_points: 100
  obs:
    noise_clean: 0.01
    noise_noisy: 1.0
    nt: 67
    nx1: 10
    nx2: 10
    ratio_clean: 0.8
  pde_points: 2160
fine_tune:
  adam_epochs: 2000
  lambda_b: 1.0
  lambda_d: 1.0
  lambda_r: 0.005
  lbfgs_iter: 500
  lr_adam: 0.001
model:
  hidden_dim: 100
  hidden_layers: 5
  in_dim: 2
  out_dim: 1
partition:
  eps: 0.025
  w_data: 1.0
  w_res: 0.001
pruning:
  alpha: 0.05
  layers:
  - 0
  - 2
  - 4
  - 6
  - 8
  num_iter: 20
  strategy: iterative
seed: 42
training:
  adaptive_eps: 0.001
  lambda_b_max: 1000
  lambda_d_max: 1000
  lbfgs_max_iter: 5000
  lr_pretrain: 0.001
  pretrain_epochs: 20000
